### ISSUE TITLE
Static session leads to unexpected behaviour when using multiple instances of GW2Client

### ISSUE THREAD

**Issue by shoeffner** [JuxhinDB/gw2-api-interface#4]
The `BaseAPIObject` uses [`self.session = GuildWars2Client.session`](https://github.com/JuxhinDB/gw2-api-interface/blob/e716c0e266eda8effe07f50897fd02db1b101e9a/gw2api/objects/base_object.py#L38) to assign the static session to use.

Unfortunately this results in the following unexpected behaviour:
```python
from gw2api import GuildWars2Client as gw2c
api_nonauth = gw2c()
api_auth = gw2c(api_key='1C5570FC-6A45-5F40-951B-693179A5C85CB637890C-4651-492C-A6E9-8254B7B52B7C')
print('not authorized', api_nonauth.tokeninfo.get())
print('authorized', api_auth.tokeninfo.get())
```
```
not authorized {'text': 'endpoint requires authentication'}
authorized {'text': 'endpoint requires authentication'} 
```

The authorized instance uses the same session as the unauthorized instance. Similarly, when creating them in the opposite order, the unauthorized session will happily use the previous API key:

```python
from gw2api import GuildWars2Client as gw2c
api_auth = gw2c(api_key='1C5570FC-6A45-5F40-951B-693179A5C85CB637890C-4651-492C-A6E9-8254B7B52B7C')
api_nonauth = gw2c()
print('not authorized', api_nonauth.tokeninfo.get())
print('authorized', api_auth.tokeninfo.get())
```
```
not authorized {'id': '1C5570FC-6A45-5F40-951B-693179A5C85C', 'name': 'Public', 'permissions': ['account']}
authorized {'id': '1C5570FC-6A45-5F40-951B-693179A5C85C', 'name': 'Public', 'permissions': ['account']}
```

I think to solve this issue, it might better to create the API Objects per instance of `GuildWars2Client` instead of once in advance, and assigning them an instance-level session during creation. But I am not sure, if there are other ways -- it might be enough to change [these lines](https://github.com/JuxhinDB/gw2-api-interface/blob/e716c0e266eda8effe07f50897fd02db1b101e9a/gw2api/__init__.py#L80-L83) to copy the API Objects and reassign their sessions, i.e. changing:
```python
objects = API_OBJECTS

for object_ in objects:
    setattr(self, object_.__class__.__name__.lower(), object_)
```
to
```python
import copy  # somewhere above

objects = API_OBJECTS

for object_ in objects:
    object_ = copy.copy(object_)
    object_.session = self.session  # self is the current client instance
    setattr(self, object_.__class__.__name__.lower(), object_)
```
alongside
```python
self.session = self.__build_requests_session()
GuildWars2Client.session = self.session
```
in `GuildWars2Client.__init__`.

This is at least a quick fix, but I am still to come up with a nice and clean way. Maybe an API Object factory which takes the session as an argument and then creates all the `API_OBJECTS`?

**Comment by JuxhinDB** [comment]
Hey @shoeffner -- thanks for the report. Looking back at this, I can immediately see this being an issue. The `Session` object should be per instance and not static. Taking a close look at this and will push a fix shortly. Will let you know. :-)

EDIT: Make sure that that API key is a test API key. I would not recommend throwing that around in public especially if it has write privileges.

**Comment by shoeffner** [comment]
Thank you for the heads up. 
I don't think any of the API keys do have write access (there is no functionality like that, or is there?), and this one only has the minimum account permissions, so I think it's fine (I'm okay with people knowing my account name and creation and home world etc). I even labeled it public so that I know that it's out there, worst case I can still delete it at any point.

**Comment by JuxhinDB** [comment]
Do not worry, was just a word of caution in general so long as you are aware. :-)

---

Onto the issue.

I have pushed the following [commit](https://github.com/JuxhinDB/gw2-api-interface/commit/ac23480d5ad4d19e369ef7d3eddcdc3fc0fbcc2b) which effectively removes `GuildWars2Client.session` as a class variable into an instance variable that is injected into the `BaseObject` as seen [here](https://github.com/JuxhinDB/gw2-api-interface/blob/ac23480d5ad4d19e369ef7d3eddcdc3fc0fbcc2b/gw2api/__init__.py#L84):

```python
for object_ in objects:
        object_ = copy.copy(object_)
        object_.session = self.session
        setattr(self, object_.__class__.__name__.lower(), object_)
```

With your example, I now get the following outcome:

```python
>>> from gw2api import GuildWars2Client as gw2c
>>> api_auth = gw2c(api_key='1C5570FC-6A45-5F40-951B-693179A5C85CB637890C-4651-492C-A6E9-8254B7B52B7C')
>>> api_nonauth = gw2c()
>>> print('not authorized', api_nonauth.tokeninfo.get())
>>> print('authorized', api_auth.tokeninfo.get())

not authorized {'text': 'endpoint requires authentication'}
authorized {'id': '1C5570FC-6A45-5F40-951B-693179A5C85C', 'name': 'Public', 'permissions': ['account']}
```

If you call `BaseObject.get()` prior to instantiating a client, you now get the following `AssertionError`:

```python
>>> API_OBJECTS[0].get()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\jdb.ACX\Projects\gw2-api-interface\gw2api\objects\api_version_1\__init__.py", line 7, in get
    response = super().get()
  File "C:\Users\jdb.ACX\Projects\gw2-api-interface\gw2api\objects\base_object.py", line 46, in get
    assert isinstance(self.session, Session), "BaseObject.session is not yet instantiated. Make sure an instance" \
AssertionError: BaseObject.session is not yet instantiated. Make sure an instanceof GuildWars2APIClient is created first to be able to send requests.
```

--- 

Do you mind pulling latest `master` and letting me know if thing suits your needs?

**Comment by shoeffner** [comment]
Thanks a lot, it works exactly as I wished it to work! Thanks for the really quick resolution.
